config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]

  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends'  , to: 'users#my_friends'
  get 'search_user' , to: 'users#search'
  get 'search_stock', to: 'stocks#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new( publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
                                   endpoint: 'https://sandbox.iexapis.com/v1' )
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonimous"
  end


end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  helper_method :logged_in?, :has_empty_objects, :not_friends_with?

  def has_empty_objects?(array)
    if !array.nil?
      array.each do |object|
        return object.nil?
      end
    else
      return array.blank?
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "Now following '#{friend.first_name} #{friend.last_name}'."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Removed from friend list."
    redirect_to my_friends_path
  end


end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

 def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/stock_result'}
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Stock (Ticker) Symbol not found or inexistent"
          format.js { render partial: 'users/stock_result'}
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a Stock (Ticker) Symbol to search"
        format.js { render partial: 'users/stock_result'}
      end
    end
 end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock '#{stock.name}' added successfully."
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "'#{stock.name}' removed from tracking list."
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @friend_list = @user.friends
    @tracked_stocks = @user.stocks
  end

  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friend_list = current_user.friends
  end

  def search_by_names(first_name, last_name)
    user = User.where("first_name = ? and last_name = ?","#{first_name}", "#{last_name}")
    return user unless !user
      return nil
  end

  def search_by_email(email)
    user = User.where("email = ?" , "#{email}")
    return user unless !user
      return nil
  end

  def render_search_results(user)
    if has_empty_objects?(user)
      flash.now[:alert] = "User not found or inexistent."
    end
    respond_to do |format|
      format.js { render partial: 'users/friend_result'}
    end
  end

  def search
    if params[:first_name].present? && params[:last_name].present?
      @user = search_by_names(params[:first_name], params[:last_name])
    elsif params[:email].present?
      @user = search_by_email(params[:email])
    end
    render_search_results(@user)
  end

  def not_friends_with?(user, user_id)
    !user.friendships.where(friend_id: user_id).exists?
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friendhips/_list.html.erb
<div class="row">
  <div class="col-11">
    <table class="table table-bordered table-dark">
      <thead>
        <tr class="text-center">
          <th scope="col">#</th>
          <th scope="col">First name</th>
          <th scope="col">Last name</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% row_number = 1 %>
        <% @friend_list.each do |friend| %>
        <tr class="text-center">
          <th scope="row"><%= row_number %></th>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= link_to "Stop following", users_path(friend), method: :delete, data: {confirm: "Are you sure?"},
              class:"btn btn-sm btn-warning" %></td>
        </tr>
        <% row_number+=1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/friendships/_list.html.erb
<div class="row">
  <div class="col-11">
    <table class="table table-sm table-bordered table-dark">
      <thead>
        <tr class="text-center">
          <th scope="col">#</th>
          <th scope="col">First name</th>
          <th scope="col">Last name</th>
          <th scope="col">Email</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% row_number = 1 %>
        <% @friend_list.each do |friend| %>
        <tr class="text-center">
          <th scope="row"><%= row_number %></th>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td>
            <%= link_to "View profile", user_path(friend.id), class:"btn btn-sm btn-info" %>
            <%= link_to "Stop following", friendship_path(friend), method: :delete, class:"btn btn-sm btn-danger" %>
          </td>
        </tr>
        <% row_number+=1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if alert.present? %>
<div class="alert alert-danger text-center" role="alert" style="margin-top:15px;">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

<% if notice.present? %>
<div class="alert alert-info text-center" role="alert" style="margin-top:15px;">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <%= link_to "Finance Tracker", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
        <%= link_to "My Portfolio", my_portfolio_path, class:"nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
        <%= link_to "My Friends", my_friends_path, class:"nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to edit_user_registration_path, class:"dropdown-item" do %>
           <%= fa_icon "edit" %> Profile
          <% end %>          
        </div>
      </li>
    </ul>
    <div class="username_tag navbar-text">
      <%= current_user.full_name %>
    </div>
    <%= button_to "Logout", destroy_user_session_url, method: :delete, class:"btn btn btn-danger" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-11">
    <table class="table table-sm table-bordered table-dark">
      <thead>
        <tr class="text-center">
          <th scope="col">#</th>
          <th scope="col">Ticker (Symbol)</th>
          <th scope="col">Name</th>
          <th scope="col">Last price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% row_number = 1 %>
        <% @tracked_stocks.each do |stock| %>
        <tr class="text-center">
          <th scope="row"><%= row_number %></th>
          <td><%= stock.ticker %></td>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <td><%= link_to "Remove", user_stock_path(stock), method: :delete, data: {confirm: "Are you sure?"},
              class:"btn btn-sm btn-warning" %></td>
        </tr>
        <% row_number+=1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @user %>
<table class="table table-hover table-sm">
  <tbody>
    <% @user.each do |user| %>
    <tr>
      <td><strong>Name: </strong> <%= user.first_name %></td>
      <td><strong>Last name: </strong> <%= user.last_name %></td>
      <td><strong>Mail: </strong> <%= user.email %></td>
      <td><strong>Actions: </strong>
        <%= link_to "View profile", user_path(user.id), class:"btn btn-sm btn-info" %>
        <% if not_friends_with?(current_user, user.id) %>
          <%= link_to "Follow", friendships_path(friend: user), class:"btn btn-sm btn-primary", method: :post %>
        <% else %>
          <span class="">Already friends</span>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#results').innerHTML = "<%= j render 'users/friend_result.html' %>"

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
<div class="card card-header results-block mb-3">
  <strong>Symbol: </strong> <%= @stock.ticker %>
  <strong>Name: </strong> <%= @stock.name %>
  <strong>Price: </strong> <%= @stock.last_price %>
  <strong>Action: </strong>
  <% if current_user.can_track_stock?(@stock.ticker) %>
    <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker), class:"btn btn-sm btn-success", method: :post %>
  <% else %>
    <i> Already tracking </i>
    <% if !current_user.under_stock_limit? %>
    <i> 10 stocks. </i>
    <% end %>
    <% if current_user.stock_already_tracked?(@stock.ticker) %>
    <i> this stock. </i>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/users/_search_forms.html.erb
<div class="search-area">
  <h4 class="search-title">Search users to follow!</h4>
  <%= form_tag search_user_path, remote: true, method: :get do %>
  <div class="row">
    <div class="col-md-6">
      <div class="input-group mb-4">
        <%= text_field_tag :first_name, params[:first_name], autofocus: true, placeholder:"First name", class:"form-control form-control-sm" %>
        <%= text_field_tag :last_name, params[:last_name], placeholder:"Last name", class:"form-control form-control-sm" %>
        <div class="input-group-append">
          <%= button_tag "Search", type: :submit, class:"btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
    </div>
    <small id="names-help" class="form-text text-muted"> * Please complete both to search.</small>
  </div>
  <% end %>
  <%= form_tag search_user_path, remote: true, method: :get do %>
  <div class="row">
    <div class="col-md-6">
      <div class="input-group mb-4">
        <%= text_field_tag :email, params[:email], autofocus: true, placeholder:"Email", class:"form-control form-control-sm" %>
        <div class="input-group-append">
          <%= button_tag "Search", type: :submit, class:"btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/_search_friend_form.html.erb
<div class="search-area">
  <h4 class="search-title">Search users to follow!</h4>
  <%= form_tag search_user_path, remote: true, method: :get do %>
  <div class="row">
    <div class="col-md-6">
      <div class="input-group">
        <%= text_field_tag :first_name, params[:first_name], autofocus: true, placeholder:"First name", class:"form-control form-control-sm" %>
        <%= text_field_tag :last_name, params[:last_name], placeholder:"Last name", class:"form-control form-control-sm" %>
        <div class="input-group-append">
          <%= button_tag "Search", type: :submit, class:"btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
    </div>
    <small id="names-help" class="form-text text-muted"> * Please complete both to search.</small>
  </div>
  <% end %>
  <%= form_tag search_user_path, remote: true, method: :get do %>
  <div class="row">
    <div class="col-md-6">
      <div class="input-group">
        <%= text_field_tag :email, params[:email], autofocus: true, placeholder:"Email", class:"form-control form-control-sm" %>
        <div class="input-group-append">
          <%= button_tag "Search", type: :submit, class:"btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/_search_stock_form.html.erb
<div class="search-area">
  <h4 class="search-title">Search stocks</h4>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
  <div class="row">
    <div class="col-md-5">
      <div class="input-group">
        <span class="input-group-text">
          <%= fa_icon "search" %>
        </span>
        <%= text_field_tag :stock, params[:stock], placeholder:"Ticker / Symbol", class:"form-control" %>
        <div class="input-group-append">
          <%= button_tag "Search", type: :submit, class:"btn btn-outline-secondary" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/_stock_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
<div class="card card-header results-block mb-3">
  <strong>Symbol: </strong> <%= @stock.ticker %>
  <strong>Name: </strong> <%= @stock.name %>
  <strong>Price: </strong> <%= @stock.last_price %>
  <strong>Action: </strong>
  <% if current_user.can_track_stock?(@stock.ticker) %>
    <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker), class:"btn btn-sm btn-success", method: :post %>
  <% else %>
    <i> Already tracking </i>
    <% if !current_user.under_stock_limit? %>
    <i> 10 stocks. </i>
    <% end %>
    <% if current_user.stock_already_tracked?(@stock.ticker) %>
    <i> this stock. </i>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/users/_stock_result.js.erb
document.querySelector('#results').innerHTML = "<%= j render 'users/stock_result.html' %>"

app/views/users/my_friends.html.erb
<h1>My friends</h1>

<%= render 'users/search_friend_form' %>

<div id="results">
</div>

<% if !@friend_list.empty? %>
  <%= render 'friendships/list' %>
<% else %>
  <p>Your friends will be displayed here when added.</p>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>

<%= render 'users/search_stock_form' %>

<div id="results">
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <p>No stocks tracked yet.</p>
<% end %>

app/views/users/show.html.erb
<h1>View profile</h1>

<div class="card text-center text-white bg-dark">
  <div class="card-header">
    <ul class="nav nav-pills card-header-pills">
      <li class="nav-item">
        <span class="nav-link text-white disabled">
          <h4><%= "#{@user.first_name} #{@user.last_name}" %></h4>
        </span>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <tr class="text-center">
      <% if !@friend_list.empty? %>
        <%= render 'friendships/list' %>
         <% else %>
        <p>This user doesnt follow anyone.</p>
      <% end %>
    </tr>
  </div>
  <div class="card-body">
    <tr>
      <% if !@tracked_stocks.empty? %>
        <%= render 'stocks/list' %>
      <% else %>
        <p>This isnt tracking any Stock.</p>
      <% end %>
    </tr>
  </div>
  <div class="card-footer ">
    <% if not_friends_with?(current_user, @user.id) %>
      <%= link_to "Follow", friendships_path(friend: @user), class:"btn fluid btn-primary", method: :post %>
    <% else %>
      <span class="btn btn-success active">Already friends</span>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome, <%="#{current_user.first_name}"%>!</h1>

<div class="jumbotron">
  <h2 class="display-4"></h2>
  <p class="lead">
    With this application you can track Ticker Stocks from any brand and follow anyone registered with their own tracked stocks.
    <br><br>It's really simple. Just follow this next instructions to start!
  </p>

  <hr class="my-4">
  <p>To search stock companies using ticker, go to :
  <%= link_to "My Portfolio", my_portfolio_path, class:"btn btn-primary btn-sm" %></p>
  <p>To look for other users and manage your friendlist :
  <%= link_to "My Friends", my_friends_path, class:"btn btn-primary btn-sm" %></p>
</div>